config/routes.rb
Rails.application.routes.draw do
  devise_for :autors
  # resources :comentarios
  # get 'articulos/new'

  # get 'articulos/index'

  resources :articulos do
    resources :comentarios
  end

  get 'estaticas/contacto'

  get 'estaticas/nosotros'

  get 'home/index'
  root "articulos#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  belongs_to :autor, optional: true
  has_many :comentarios, dependent: :destroy

  validates :titulo, presence: {:message => "no puede estar vacío"}
  validates :contenido, presence: {:message => "no puede estar vacío"}, length: {minimum: 50, :message => "es demasiado corto, mínimo 50 caracteres"}
end

app/models/autor.rb
class Autor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
  has_many :comentarios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def index
    @articulos = Articulo.all.order("created_at DESC")
  end

  def new
    @articulo = Articulo.new
    @boton = "Crear"
  end

  def create
    @articulo = Articulo.new(articulo_params)
    if @articulo.save
      redirect_to @articulo
    else
      render 'new'
    end
  end

  def edit
     @articulo = Articulo.find(params[:id])
     @boton = "Modificar"
  end

  def update
    @articulo = Articulo.find(params[:id])
    if @articulo.update(articulo_params)
      flash[:notice] = "Artículo modificado correctamente"
      redirect_to @articulo
    else
      render 'edit'
    end
  end

  def show
    @articulo = Articulo.find(params[:id])
  end

  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy
    redirect_to articulos_path :notice => "Artículo eliminado correctamente"
  end

  private
    def articulo_params
      params.require(:articulo).permit(:titulo, :contenido)
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_articulo, only: [:create, :destroy]

  def create
    # @articulo = Articulo.find(params[:articulo_id])

    @comentario = @articulo.comentarios.create(comentario_params)
    redirect_to @articulo
  end

  def destroy
    # @articulo = Articulo.find(params[:articulo_id])
    @comentario = @articulo.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to @articulo
  end

  private

    def comentario_params
      params.require(:comentario).permit(:nombre, :texto, :articulo_id)
    end
    def set_articulo
    @articulo = Articulo.find(params[:articulo_id])
  end

end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
  end

  def nosotros
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/_form.html.erb
<%= form_for @articulo do |f| %>
  <%= f.label :titulo %><br>
  <%= f.text_field :titulo %><br>
  <%= f.label :contenido %><br>
  <%= f.text_area :contenido %><br>

  <%= f.submit "#{@boton} Artículo" %>
  
  <% if @articulo.errors.any? %>
    <div id="errors">
      <h2>Se han producido los siguientes errores: </h2>
      <ul>
        <% @articulo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/articulos/edit.html.erb
<h1><Articulos#edit></Articulos></h1>
<p>Find me in app/views/articulos/edit.html.erb</p>
<%= render 'form' %>

app/views/articulos/index.html.erb
<h1>Articulos#index</h1>
<% @articulos.each do |art| %>
<h2>
  <%= link_to art.titulo, art %>
</h2>
<p>Creado el
  <%= art.created_at.strftime("%d-%m-%Y") %>
</p>
<p>
<p>
  <%= art.contenido.truncate_words(30) %>
</p>
</p>
<% end %>

<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>
<p>Find me in app/views/articulos/new.html.erb</p>

<%= render 'form' %>

app/views/articulos/show.html.erb
<h1><%= @articulo.titulo %></h1>
<p>Creado el  <%= @articulo.created_at.strftime("%d-%m-%Y") %></p>
<p><%= @articulo.contenido %></p>

<%= link_to "Editar", edit_articulo_path(@articulo) %>
<%= link_to "Eliminar", @articulo, :method => :delete, data: {confirm: "¿Seguro que quieres eliminar el artículo?"} %>

<p><%= @articulo.comentarios.count %> Comentarios</p>
<%= render @articulo.comentarios %>
<br>
<p>Deja tu comentario:</p>
<%= render 'comentarios/form' %>

app/views/comentarios/_comentario.html.erb
<div>
  <p><%= comentario.nombre %></p>
  <p><%= comentario.texto %></p>
  <p>Creado el	<%= comentario.created_at.strftime("%d-%m-%Y") %></p>
</div>

<%= link_to "Eliminar", [comentario.articulo, comentario], :method => :delete, data: {confirm: "¿Seguro que quieres eliminar el comentario?"} %>

app/views/comentarios/_form.html.erb
<%= form_for([@articulo, @articulo.comentarios.build]) do |form| %>
  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :comentario_nombre %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto, id: :comentario_texto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estaticas/contacto.html.erb
<h1>Página de contacto</h1>
<p>bla bla bla bla</p>

<%= content_for :saludo, "Hola" %>
<%= yield :saludo %>

app/views/estaticas/nosotros.html.erb
<h1>Página de nosotros</h1>
<p>en esta pagina vamos a mostrar la info sobre nosotros</p>

app/views/home/index.html.erb
<h1>Hola</h1>
<p>¡Bienvenidos a nuestro Blog! 6</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <ul>
        <% flash.each do |key, value| %>
          <li><%= value %></li>
        <% end %>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>
<%= link_to 'Nosotros', estaticas_nosotros_path %>